const dashboardUrl = "/api/v1/dashboard";
const insightUrl = "/api/v1/insight";

const avgPriceEl = document.querySelector("#avgPrice");
const forecastPriceEl = document.querySelector("#forecastPrice");
const anomalyCountEl = document.querySelector("#anomalyCount");
const trendEl = document.querySelector("#trend");
const farmerEl = document.querySelector("#farmerInsight");
const traderEl = document.querySelector("#traderInsight");
const analystEl = document.querySelector("#analystInsight");
const limitEl = document.querySelector("#limit");
const commodityEl = document.querySelector("#commodity");
const refreshBtn = document.querySelector("#refreshBtn");
const insightBtn = document.querySelector("#insightBtn");
const insightTextEl = document.querySelector("#insightText");
const insightSourceEl = document.querySelector("#insightSource");
const contextEl = document.querySelector("#context");

let chart;

function formatCurrency(value) {
  return new Intl.NumberFormat("en-IN", { maximumFractionDigits: 2 }).format(value);
}

function setError(message) {
  insightTextEl.textContent = message;
  insightTextEl.classList.add("error");
}

function clearError() {
  insightTextEl.classList.remove("error");
}

function renderChart(series, anomalies) {
  const anomalySet = new Set(anomalies.map((a) => a.index));
  const labels = series.map((point) => point.index);
  const data = series.map((point) => point.modal_price);
  const anomalyData = series.map((point) => (anomalySet.has(point.index) ? point.modal_price : null));

  if (chart) {
    chart.destroy();
  }

  chart = new Chart(document.querySelector("#priceChart"), {
    type: "line",
    data: {
      labels,
      datasets: [
        {
          label: "Modal Price",
          data,
          borderColor: "#0f766e",
          backgroundColor: "rgba(15, 118, 110, 0.18)",
          fill: true,
          tension: 0.28,
          pointRadius: 0,
        },
        {
          label: "Anomaly",
          data: anomalyData,
          borderColor: "#b42318",
          backgroundColor: "#b42318",
          showLine: false,
          pointRadius: 5,
        },
      ],
    },
    options: {
      responsive: true,
      maintainAspectRatio: true,
      plugins: {
        legend: {
          labels: {
            usePointStyle: true,
          },
        },
      },
      scales: {
        y: {
          ticks: {
            callback: (value) => `Rs ${value}`,
          },
        },
      },
    },
  });
}

async function fetchDashboard() {
  const limit = Number.parseInt(limitEl.value, 10) || 120;
  const commodity = commodityEl.value.trim();
  const params = new URLSearchParams({ limit: String(limit) });
  if (commodity) {
    params.set("commodity", commodity);
  }

  const res = await fetch(`${dashboardUrl}?${params.toString()}`);
  if (!res.ok) {
    throw new Error("Failed to load dashboard data");
  }

  return res.json();
}

function updateDashboard(payload) {
  avgPriceEl.textContent = `Rs ${formatCurrency(payload.average_price)}`;
  forecastPriceEl.textContent = `Rs ${formatCurrency(payload.forecast_price)}`;
  anomalyCountEl.textContent = payload.anomaly_count;
  trendEl.textContent = payload.trend;

  farmerEl.textContent = payload.agents.farmer;
  traderEl.textContent = payload.agents.trader;
  analystEl.textContent = payload.agents.analyst;

  renderChart(payload.series, payload.anomalies);
}

async function loadDashboard() {
  refreshBtn.disabled = true;
  refreshBtn.textContent = "Loading...";
  try {
    const payload = await fetchDashboard();
    updateDashboard(payload);
  } catch (error) {
    setError(error.message || "Unable to load dashboard");
  } finally {
    refreshBtn.disabled = false;
    refreshBtn.textContent = "Refresh Dashboard";
  }
}

async function generateInsight() {
  insightBtn.disabled = true;
  insightBtn.textContent = "Generating...";
  clearError();
  insightTextEl.textContent = "";

  try {
    const res = await fetch(insightUrl, {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({
        limit: Number.parseInt(limitEl.value, 10) || 120,
        commodity: commodityEl.value.trim() || null,
        context: contextEl.value.trim() || null,
      }),
    });

    if (!res.ok) {
      throw new Error("Unable to generate insight");
    }

    const payload = await res.json();
    insightTextEl.textContent = payload.insight;
    insightSourceEl.textContent = `Generated by: ${payload.source}`;
  } catch (error) {
    setError(error.message || "Insight generation failed");
  } finally {
    insightBtn.disabled = false;
    insightBtn.textContent = "Generate Insight";
  }
}

refreshBtn.addEventListener("click", loadDashboard);
insightBtn.addEventListener("click", generateInsight);

loadDashboard();
